# Generated by Django 3.2.3 on 2023-06-18 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20230618_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('id', django.db.models.expressions.F('user_id')), ('contacts__isnull', False), _connector='OR'), related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
